### ISSUE TITLE
Add info when the next batch of flips will come

### ISSUE THREAD

**Issue by matthias-luger** [Coflnet/SkyCommands#4]
Premium users want to know when the next batch of flips comes in. You could send it with the last flip of a batch or as a websocket answer with the subFlip (needs to be discussed so it doesnt break anything).
Just guessing (like always 30sek after the last flip) in the UI is not enough as people want to rely on the feature.

**Comment by matthias-luger** [comment]
Needed for https://github.com/Coflnet/hypixel-react/issues/424

**Comment by Ekwav** [comment]
https://sky-commands.coflnet.com/api/flip/update/when

Returns the update timestamp of the last update. 
All future updates are in roughly 60 second intervals

**Comment by Ekwav** [comment]
Basically done, only waiting for merge conflicts to be resolved within https://github.com/Coflnet/hypixel-react/issues/424
