### ISSUE TITLE
Aspect ratio of some images

### ISSUE THREAD

**Issue by matthias-luger** [Coflnet/SkyCommands#45]
Is there a reason why some images (i think all heads) dont have the same width and height?

https://sky.coflnet.com/static/icon/SHADOW_ASSASSIN_HELMET for example has 64x59
while non-heads are 64x64
https://sky.coflnet.com/static/icon/AURORA_CHESTPLATE

Not a big issue, mostly curios

**Comment by Ekwav** [comment]
Depends on the resource pack or the rendering by default images are (tried) to be pulled through https://sky.shiiyu.moe/item/SHADOW_ASSASSIN_HELMET 
as a fallback for new items mc-heads.net 
TLDR: no there is no special reason
